### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Wasiiiii** [bfshi/DGAM-Weakly-Supervised-Action-Localization#3]
Traceback (most recent call last):
  File "test.py", line 80, in <module>
    main()
  File "test.py", line 31, in main
    logger = create_logger(config, 'test')
  File "C:\Users\Wasif\Prog\lib\utils\utils.py", line 75, in create_logger
    logging.basicConfig(filename=str(final_log_file),
  File "C:\Users\Wasif\anaconda3\envs\DGAM\lib\logging\__init__.py", line 1976, in basicConfig
    h = FileHandler(filename, mode)
  File "C:\Users\Wasif\anaconda3\envs\DGAM\lib\logging\__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\Wasif\anaconda3\envs\DGAM\lib\logging\__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Wasif\\Prog\\experiments\\THUMOS14\\test\\THUMOS14_2020-06-02-02-09_test.log'

**Comment by bfshi** [comment]
Hi Wasif, thanks for pointing our this! I think you could create a direction `/experiments/THUMOS14/test/` and it will be fine.
Same for ActivityNet12.
I've updated the repo accordingly, please check, thanks!
